# Generated by Django 5.2.7 on 2025-10-30 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="chat_messages.message",
            ),
        ),
    ]
