# Generated by Django 5.2.7 on 2025-10-31 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0002_alter_media_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
